FROM scratch
MAINTAINER Manfred Touron <m@42.am> (@moul)
# http://ftp.arm.slackware.com/slackwarearm/slackwarearm-devtools/minirootfs/roots/slack-current-miniroot_21Jul14.tar.xz
ADD slack-current-miniroot_21Jul14.tar.gz /
CMD ["/bin/bash"]
