FROM scratch
MAINTAINER Manfred Touron <m@42.am> (@moul)
# http://ftp.arm.slackware.com/slackwarearm/slackwarearm-devtools/minirootfs/roots/slack-13.37-miniroot_01May11.tar.xz
ADD slack-13.37-miniroot_01May11.tar.xz /
CMD ["/bin/bash"]
