FROM scratch
MAINTAINER Manfred Touron <m@42.am> (@moul)
# http://ftp.arm.slackware.com/slackwarearm/slackwarearm-devtools/minirootfs/roots/slack-14.0-miniroot_15Jul13.tar.xz
ADD slack-14.0-miniroot_15Jul13.tar.xz /
CMD ["/bin/bash"]
